In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel("/home/prajith_v/coding/datasets/FMC Avg SKU Rates 2017.xlsx")

In [3]:
xls = pd.ExcelFile('/home/prajith_v/coding/datasets/FMC Avg SKU Rates 2017.xlsx')
data1 = pd.read_excel(xls, '2019')
data2 = pd.read_excel(xls, '2018')
data3 = pd.read_excel(xls,'2017')

In [10]:
data3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,SKU's,Average Yearly Rate,Jan,Feb,Mar,Apr,May,June,July,Aug,Sept,Oct,Nov,Dec
1,NaN,NaN,Beans(French),46.4,32.67,37.69,49.98,80.83,91.37,69.29,46.94,47.63,47.68,57.81,39.28,26.46
2,NaN,NaN,Beans(Local),32.49,27.05,33.27,43.11,63.98,64.55,42.97,32,30.75,28.08,34.57,22.73,17.43
3,NaN,NaN,Bitter Gourd,23.91,28,34.56,37.24,40.24,40.29,37.75,26.99,20.49,14.49,19.1,20.75,14.53
4,NaN,NaN,Chilli(Long),28.28,24.8,21.91,21,26.67,37.43,35.94,39.76,26.8,13.99,21.39,23.24,13.27
5,NaN,NaN,Chilli(Bajji),22.83,22.83,28.71,32,46.82,38.08,44.14,39.9,45,23,26,20,16.84
6,NaN,NaN,Ridge Gourd,21.57,24.8,32.76,29.26,20.08,20.64,21.76,18.71,12.91,19.86,26.45,24.48,16.49
7,NaN,NaN,Capsicum (Green),26.11,21.82,20.34,23.8,17.87,19.71,23.43,30.43,31.01,23.28,42.82,44.18,25.25
8,NaN,NaN,Brinjal (Bottle Black),31.78,10.47,15.97,29.37,45.37,36.84,39.28,37.58,45.3,38.06,31.96,36.29,17.43
9,NaN,NaN,Beans (Cow Pea),31.51,31.56,34.7,35.19,34.96,34.92,27.5,28.67,33.56,32.92,31.28,28.29,24.5
10,NaN,NaN,Carrot(Local),34.98,9.51,13.46,22.13,42.1,51.6,54.29,47.7,39.1,23.86,32.59,59.98,48.35
11,NaN,NaN,Beetroot,22.94,7.74,8.27,20.19,29.6,29.81,21.02,20.93,24.38,24.62,32.32,32.29,17.87
12,NaN,NaN,Brinjal (Long Green),24.96,16.38,15.94,24.72,38.48,29.79,22.85,34.24,24.79,19.29,28.09,31.13,14.63
13,NaN,NaN,Tomato (Hybrid-Std),21.88,9.1,19.21,19.4,8.31,7.28,19.89,51.12,31.28,12.66,24.72,28.92,10.48
14,NaN,NaN,Lady's Finger,18.21,35,41.5,25,19,15.08,24.98,25.55,17.62,15.9,16.58,19.01,17.59
15,NaN,NaN,Cucumber(English),21.02,25.29,18.02,14.42,19.55,26.7,23.46,23.57,18.48,14.46,26.47,26.15,17.3
16,NaN,NaN,Cucumber(Indian),12.49,23.31,5.2,10.69,11.33,17.78,13.79,14.81,6.86,8.58,18.22,7.83,5.53
17,NaN,NaN,Tomato (Local),19.34,9.57,20.69,19.4,8.25,6.54,22.19,51.44,30.34,11.49,23.44,25.68,7.94
18,NaN,NaN,Raddish,14.62,13.72,7.52,8.53,17,17.89,15.59,15.89,13.09,17.25,25.92,16.09,7.42
19,NaN,NaN,Knol Khol,19.59,21.22,18.01,11.3,21.37,23.37,33.98,35.93,10.54,26.66,30.03,20.8,7.99
20,NaN,NaN,Chow Chow,15.96,7.89,10.33,14.31,35.46,37.04,29.96,20.52,17.02,11.65,11.2,10.57,7.67
21,NaN,NaN,Snake gourd,15.56,16.87,20.57,27.13,27.05,19.17,14.33,13.14,13.1,13.49,13.65,12.94,9
22,NaN,NaN,Cabbage (Local),12.14,4.08,4.24,9.48,14.93,19.54,10.81,7.21,10.79,14.42,33,28.88,12.77
23,NaN,NaN,Ivy Gourd,14.7,18.27,14.57,17.45,14.48,12.36,9.06,13.37,15.9,8.91,16.41,17.23,15.76
24,NaN,NaN,Cauliflower,11.73,11.38,20,16,13,11,13,10,12,13,11,7,9
25,NaN,NaN,BottleGourd,14.88,10.86,13.73,17.06,12.94,11.32,10.04,13.16,14.41,16.83,22,18.41,11.96

In [8]:
st = "Unnamed: "
beans_french=[]
for i in range(12):
    name = st+str(i+4)
    beans_french.append(data1[name].values[1])
beans_french = [data]

TypeError: Required argument 'object' (pos 1) not found